server:
  port: 8080
jwt:
  secret: ${JWT_SECRET}
minio:
  host: ${MINIO_HOST}
  user: ${MINIO_ROOT_USER}
  password: ${MINIO_ROOT_PASSWORD}
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}